name: CI/CD Docker

on:
  push:
    branches:
      - main  # Déclencher le workflow à chaque push sur main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build de l'image Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/modele-lgbm .

      - name: Push de l'image Docker
        run: docker push ${{ secrets.DOCKER_USERNAME }}/modele-lgbm
