name: Build and Push Streamlit App

on:
  push:
    branches:
      - main  # Déclencher le pipeline quand on push sur main
  pull_request:
    branches:
      - main  # Vérification lors des pull requests

env:
  DOCKERFILE_PATH: docker/streamlit_application  # Chemin du Dockerfile Streamlit

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/streamlit-app $DOCKERFILE_PATH

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/streamlit-app
